### ISSUE TITLE
Enum Proto3: Reset field ID must start at 0

### ISSUE THREAD

**Issue by anhldbk** [ripwu/vscode-ext-protobuf-helper#1]
Hey, 

Thank you for this beautiful extension. It helps me alot.

There's a nasty bug after using your extension on Enums. `Protoc` explains that: `The first enum value must be zero in proto`. 

Would you please help me troubleshoot this error?

Thank you @ripwu!

**Comment by bhargavrpatel** [comment]
If the `enum` is nested within a message, it enumerates the fields at zero.

**Comment by huang12zheng** [comment]
I've already fixed it. please give a check
@bhargavrpatel  @ripwu  @anhldbk

**Comment by anhldbk** [comment]
@huang12zheng Thank you. It works.
